EpicFantasies/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

from epicfantasiesapp.views import error404
from django.conf.urls import handler404

handler404 = error404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('epicfantasiesapp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

epicfantasiesapp/urls.py
from django.urls import path
from . import views


app_name = 'epicfantasiesapp'

urlpatterns = [
    path('', views.home , name='home'),
    path('entrar', views.entrar , name='entrar'),
    path('entrar/codigodeverificacao/', views.verificacao , name='codigodeverificacao'),

    path('cadastrar', views.cadastrar , name='cadastrar'), 
    path('meuPerfil', views.perfilUsuario , name='meuPerfilU'),
    path('historias/<int:id>/', views.storyDetalhes , name='storyDetalhes'),
    path('categoria/<int:category>',views.categoria,name="categoria"),

    path('meuPerfilUpdate', views.perfilUsuarioUpdate , name='meuPerfilUpdate'),

    path('meuPerfilStory', views.meuPerfilStory , name='meuPerfilStory'),
    path('editar_historia/<int:id>/', views.editarHistoria , name='editarHistoria'),

    path('api/comentario/<int:id>/', views.comentario , name='comentario'),  
    path('api/emocao/<int:id>/', views.emocao , name='emocao'), 
    path('api/denuncia/<int:id>/', views.denuncia , name='denuncia'),  
    path('api/thumbnail/', views.thumbnail , name='thumbnail'),  
    

    path('meuPerfilAdministrador', views.perfilAdministrador , name='meuPerfilA'),
    path('feed', views.feed , name='feed'), 
    path('sair', views.sair , name='sair'),


    path('system/redirecionamento/<int:id>/', views.redirecionamento , name='redirecionamento'),


]

epicfantasiesapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.conf import settings
from django.forms.models import model_to_dict
from django.utils import timezone

def user_directory_path(instance, filename):
    user_username = instance.user.username
    now = timezone.now()
    return f'historias/{user_username}/{now.year}/{now.month}/{now.day}/{now.hour}/{now.minute}/{filename}'

class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='perfil')
    data_criacao = models.DateTimeField(auto_now_add=True)
    foto_perfil = models.ImageField(upload_to='perfil/', null=True, blank=True)
    quantidade_seguidores = models.IntegerField(default=0)
    is_administrador_sys = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
    @property
    def get_foto_perfil_url(self):
        if self.foto_perfil:
            print(type(self.foto_perfil))
            print(self.foto_perfil)
            if self.foto_perfil is None or self.foto_perfil == "None":
                return "https://via.placeholder.com/60"
            return settings.MEDIA_URL + str(self.foto_perfil)
        else:
            return "https://via.placeholder.com/60"
class RedesSociais(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    instagram = models.CharField(max_length=255, null=True, blank=True)
    facebook = models.CharField(max_length=255, null=True, blank=True)
    twitter = models.CharField(max_length=255, null=True, blank=True)
    tiktok = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return f"Redes Sociais de {self.user.username}"

class Categoria(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome



class Historias(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='historias')
    titulo = models.CharField(max_length=255)
    previu = models.TextField()
    conteudo = models.TextField(default='')  
    data_de_criacao = models.DateTimeField(default=timezone.now)  
    foto = models.ImageField(upload_to=user_directory_path, null=True, blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE,null=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.titulo

    @property
    def get_foto_story_url(self):
        if self.foto:
            return settings.MEDIA_URL + str(self.foto)
        return None

class Comentario(models.Model):
    historia = models.ForeignKey(Historias, on_delete=models.CASCADE, related_name='comentarios')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comentarios')
    data_hora = models.DateTimeField(auto_now_add=True)
    foi_alterado = models.BooleanField(default=False)
    valor_comentario = models.TextField()

    def __str__(self):
        return f"{self.user.username} comentou na história de {self.historia.user.username}"
    


class Reacao(models.Model):
    historia = models.ForeignKey(Historias, on_delete=models.CASCADE, related_name='reacoes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reacoes')
    TIPO_REACAO_CHOICES = [
        ('EXC', 'Excelente'),
        ('BOM', 'Bom'),
        ('LEG', 'Legal'),
        ('NTL', 'Não é tão legal'),
        ('NGO', 'Não gostei'),
    ]
    tipo_reacao = models.CharField(max_length=3, choices=TIPO_REACAO_CHOICES)

    def __str__(self):
        return f"{self.user.username} reagiu a história {self.historia} com: {self.tipo_reacao}"
    


class Denuncias(models.Model):
    historia = models.ForeignKey(Historias, on_delete=models.CASCADE, related_name='denuncias')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='denuncias')
    data_hora = models.DateTimeField(auto_now_add=True)
    usuario_denunciou = models.ForeignKey(User, on_delete=models.CASCADE, related_name='denuncias_feitas')

    def __str__(self):
        return f"{self.usuario_denunciou.username} denunciou a história de '{self.historia}' feita por {self.user.username}"

class TwoFactorAuth(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    verification_code = models.CharField(max_length=6)
    timestamp = models.DateTimeField(default=timezone.now)

    @classmethod
    def code_expired(cls,timestamp):
        now = timezone.now()
        time_difference = now - timestamp
        minutes_passed = time_difference.total_seconds() / 60
        return minutes_passed >= 30
    
    def __str__(self):
        return f"Código do usuário {self.user.username}: {self.verification_code}"
    

class SystemUtilities(models.Model):
    picture_ads = models.ImageField(upload_to='propaganda/', null=True, blank=True)

    @property
    def get_picture_ads_url(self):
        if self.picture_ads:
            return settings.MEDIA_URL + str(self.picture_ads)
        return None
    
    def __str__(self):
        return f"{self.get_picture_ads_url}"

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Perfil.objects.create(user=instance)
        RedesSociais.objects.create(user=instance)


@receiver(post_save, sender=User)
@receiver(post_save, sender=Perfil)
@receiver(post_save, sender=RedesSociais)
def save_user_related(sender, instance, **kwargs):
    if sender == User:
        instance.perfil.save()
        instance.redessociais.save()

epicfantasiesapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse,HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate,login, logout
from .models import Perfil,User,Historias,Comentario,Reacao,Categoria,Denuncias,TwoFactorAuth,SystemUtilities
from django.urls import reverse
import json
from django.db.models import Count
from django.db.models.functions import ExtractMonth,ExtractDay
from django.utils import timezone
from django.core.mail import send_mail
from django.conf import settings
import random
import string
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.paginator import Paginator


class BuilderStory:
    def __init__(self,historia,comentario,reacao):
        self.id = historia.id
        self.historia = historia
        self.comentario = comentario.order_by('-id')
        self.reacao = reacao
        
        self.reacaoExcelente = 0
        self.reacaoBom = 0
        self.reacaoLegal = 0
        self.reacaoNaoetaolegal = 0
        self.reacaoNaogostei = 0


        for reacao_indivudal in reacao: 
            if reacao_indivudal.tipo_reacao == Reacao.TIPO_REACAO_CHOICES[0][0]:
                self.reacaoExcelente += 1
            if reacao_indivudal.tipo_reacao == Reacao.TIPO_REACAO_CHOICES[1][0]:
                self.reacaoBom += 1
            if reacao_indivudal.tipo_reacao == Reacao.TIPO_REACAO_CHOICES[2][0]:
                self.reacaoLegal += 1
            if reacao_indivudal.tipo_reacao == Reacao.TIPO_REACAO_CHOICES[3][0]:
                self.reacaoNaoetaolegal += 1
            if reacao_indivudal.tipo_reacao == Reacao.TIPO_REACAO_CHOICES[4][0]:
                self.reacaoNaogostei += 1




def home(request):
    if SystemUtilities.objects.all().exists():
        imagem_ads = SystemUtilities.objects.all().first().get_picture_ads_url
    else:
        imagem_ads =  'https://placehold.co/1200x1200'

    return render(request,'epicfantasiesapp/pages/home.html',context={'imagem_ads':imagem_ads,},)


def entrar(request):


    if request.user.is_authenticated:
        if not request.user.perfil.is_verified:
            return redirect('/entrar/codigodeverificacao')        
        if request.user.is_superuser:
            return redirect('/admin')
        if request.user.perfil.is_administrador_sys:
            return redirect('/meuPerfilAdministrador')
        return redirect('/meuPerfil') 
    
    if request.method == "POST":
        name = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=name,password=password)
        if user is not None:
            messages.info(request, "Login Correto")
            login(request,user) 
            if not request.user.perfil.is_verified:
                return redirect('/entrar/codigodeverificacao/')
            else:
                return redirect('/meuPerfil') 
                
        
                  
                
        else:
            messages.error(request,"Login Incorreto")

        
    

    

    return render(request,'epicfantasiesapp/pages/entrar.html')


def cadastrar(request):
    if request.user.is_authenticated:
        logout(request)


    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        passwordconfirm = request.POST['passwordconfirm']
        email = request.POST['email']
        
        if password != passwordconfirm:
            messages.error(request, "As senhas não coincidem")
            return redirect('/cadastrar')
        
        if User.objects.filter(username=username).exists():
            messages.error(request, "Nome de usuário já está em uso")
            return redirect('/cadastrar')
        
        if User.objects.filter(email=email).exists():
            messages.error(request, "Email já está em uso")
            return redirect('/cadastrar')
        
        user = User.objects.create_user(username=username, email=email, password=password)
        perfil, created = Perfil.objects.get_or_create(user=user)

        login(request,user)
        return render(request,'epicfantasiesapp/pages/meuperfilusuario.html')
    

    return render(request,'epicfantasiesapp/pages/cadastrar.html')


@login_required(login_url='/entrar')
def feed(request):
    
    if not request.user.perfil.is_verified:
        return redirect('/entrar/codigodeverificacao')   
    historias = Historias.objects.filter(is_published=True)
    categorias_disponiveis = Categoria.objects.all()
    
    lista_view = []
  
    for historia in historias:
        comentario = Comentario.objects.filter(historia=historia)   
        reacao = Reacao.objects.filter(historia=historia)
        b1 = BuilderStory(historia,comentario,reacao)
        lista_view.append(b1)

    paginator = Paginator(lista_view, 10)
    pagina = request.GET.get('page')
    itens_pagina = paginator.get_page(pagina)

    
    return render(request,'epicfantasiesapp/pages/feed.html',context={"user":request.user,
                                                                      "lista_view":itens_pagina,
                                                                      "categorias_disponiveis":categorias_disponiveis,
                                                                      "is_feed":True,
                                                                      "is_detalhes":False,
                                                                      "is_meuperfil":False,
                                                                      })


@login_required(login_url='/entrar')
def perfilUsuario(request):
    if request.user.perfil.is_administrador_sys:
        return redirect('/meuPerfilAdministrador')
    if not request.user.perfil.is_verified:
        return redirect('/entrar/codigodeverificacao')   
    historias = Historias.objects.filter(user=request.user)
    categorias_disponiveis = Categoria.objects.all()
    
    lista_view_published = []
    lista_view_not_published = []

    for historia in historias:
        comentario = Comentario.objects.filter(historia=historia)   
        reacao = Reacao.objects.filter(historia=historia)
        b1 = BuilderStory(historia,comentario,reacao)
        if historia.is_published:
            lista_view_published.append(b1)
        else:
            lista_view_not_published.append(b1)






    return render(request,'epicfantasiesapp/pages/meuperfilusuario.html',context={"user":request.user,
                                                                                  "lista_view_published":lista_view_published,
                                                                                  "lista_view_not_published":lista_view_not_published,
                                                                                  "categorias_disponiveis":categorias_disponiveis,
                                                                                  "is_feed":False,
                                                                                  "is_detalhes":False,
                                                                                  "is_meuperfil":True,
                                                                                  })


@login_required(login_url='/entrar')
def perfilUsuarioUpdate(request):
    if not request.user.perfil.is_verified:
        return redirect('/entrar/codigodeverificacao')   
    user = request.user
    perfil = user.perfil
    redessociais = user.redessociais
    
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        foto_perfil = request.FILES.get('foto_perfil')
        instagram = request.POST.get('instagram')
        facebook = request.POST.get('facebook')
        twitter = request.POST.get('twitter')
        tiktok = request.POST.get('tiktok')

        if first_name and first_name != user.first_name:
            user.first_name = first_name

        if last_name and last_name != user.last_name:
            user.last_name = last_name

        if foto_perfil:
            perfil.foto_perfil = foto_perfil

        if instagram != redessociais.instagram:
            redessociais.instagram = instagram

        if facebook != redessociais.facebook:
            redessociais.facebook = facebook

        if twitter != redessociais.twitter:
            redessociais.twitter = twitter

        if tiktok != redessociais.tiktok:
            redessociais.tiktok = tiktok

        user.save()
        perfil.save()
        redessociais.save()


    return redirect('/system/redirecionamento/0/')


@login_required(login_url='/entrar')
def meuPerfilStory(request):
    if not request.user.perfil.is_verified:
        return redirect('/entrar/codigodeverificacao')   
    if request.method == 'POST':
        titulo = request.POST.get('titulo')
        previu = request.POST.get('previu')
        conteudo = request.POST.get('conteudo')
        categoria_id = request.POST.get('categoria')
        is_published = request.POST.get('is_published')
        try:
            categoria_id = int(categoria_id)
        except:
            categoria_id = None
        if not Categoria.objects.filter(id=categoria_id).exists():
            categoria_id = None

        foto = request.FILES.get('foto') if 'foto' in request.FILES else None
        if is_published =="on":
            is_published = True
        else:
            is_published = False
        
        
        historia = Historias(
            user=request.user,  
            titulo=titulo,
            previu=previu,
            conteudo=conteudo,
            categoria=Categoria.objects.filter(id=categoria_id)[0],
            foto=foto,
            is_published=is_published
        )
        historia.save()

    return redirect('/meuPerfil')

epicfantasiesapp/templates/epicfantasiesapp/pages/cadastrar.html
{% extends 'global/base.html' %}

{% block title %}Cadastrar | {% endblock title %}

{% block content %}
<div class="signup-container">
    <div class="signup-box">
        <h2>Cadastrar</h2>
        {% if messages %}
            {% for m in messages %}
                <div class="alert alert-warning" role="alert">
                    {{ m }}
                </div>
            {% endfor %}
        {% endif %}
        <form action="{% url "epicfantasiesapp:cadastrar" %}" method="post">
            {% csrf_token %}
            <div class="textbox">
                <input type="text" placeholder="Usuário" name="username" required>
            </div>
            <div class="textbox">
                <input type="email" placeholder="Email" name="email" required>
            </div>
            <div class="textbox">
                <input type="password" placeholder="Senha" name="password" required>
            </div>
            <div class="textbox">
                <input type="password" placeholder="Confirmer a senha" name="passwordconfirm" required>
            </div>
            <button type="submit" class="btn">Cadastrar</button>
            <p>Já tem uma conta? <a href="{% url "epicfantasiesapp:entrar" %}">Entre</a></p>
        </form>
    </div>
</div>

{% endblock content %}

epicfantasiesapp/templates/epicfantasiesapp/pages/categoria.html
{% extends 'global/base.html' %}

{% block title %}{{page_categoria.nome}} | {% endblock title %}

{% block content %}

    <!-- Área de Pesquisa -->
    <div class="search-container">
        <input type="text" id="search-bar" placeholder="Pesquisar...">
        <button type="button" id="search-button"><i class="fas fa-search"></i></button>
        <div class="autocomplete-suggestions" id="autocomplete-list"></div>
    </div>


    <div class="feed">

        {% for  lista_view_individual in lista_view  %}
            <div class="story-card" data-category="{{lista_view_individual.historia.categoria.id}}">
                <div class="story-header">
                    {% if lista_view_individual.historia.user.perfil.foto_perfil%}
                        <img class="avatar" src="{{lista_view_individual.historia.user.perfil.get_foto_perfil_url}}">
                    {% else %}
                        <img class="avatar" src="https://placehold.co/200x200">
                    {% endif %}
                    <div class="story-info">
                        <p class="author">{{lista_view_individual.historia.user.username}}</p>
                        <p class="date">{{lista_view_individual.historia.data_de_criacao|date:"d/m/Y H:i"}}</p>
                        <p class="date">{{lista_view_individual.historia.categoria.nome}}</p>                       
                    </div>    
                </div>
                <div class="story-info">
                    <a href="{% url "epicfantasiesapp:storyDetalhes" lista_view_individual.historia.id %}" ><p class="title">{{lista_view_individual.historia.titulo}}</p></a>
                </div>
                <div class="story-content">
                    <a href="{% url "epicfantasiesapp:storyDetalhes" lista_view_individual.historia.id %}" ><p>{{lista_view_individual.historia.previu}}</p></a>
                    {% if lista_view_individual.historia.foto%}
                        <a href="{% url "epicfantasiesapp:storyDetalhes" lista_view_individual.historia.id %}" ><img src="{{lista_view_individual.historia.get_foto_story_url}}" alt="Story Image" class="story-image"></a>
                    {% else %}
                        <a href="{% url "epicfantasiesapp:storyDetalhes" lista_view_individual.historia.id %}" ><img class="avatar" src="https://placehold.co/600x600"></a>
                    {% endif %}  
                </div>
                <div class="story-footer">
                    <div class="reaction-menu">
                        <button class="reaction-button">😊</button>
                        <div class="reaction-options">
                            <form  action="{% url 'epicfantasiesapp:emocao' lista_view_individual.historia.id %}" method="post">
                                {% csrf_token %}
                                <button class="emocoes" type="submit" value="Excelente" name="emocao">😍</button>
                                <button class="emocoes" type="submit" value="Bom" name="emocao">😀</button>
                                <button class="emocoes" type="submit" value="Legal" name="emocao">👍</button>
                                <button class="emocoes" type="submit" value="Não é tão legal" name="emocao">😢</button>
                                <button class="emocoes" type="submit" value="Não gostei" name="emocao">😡</button>
                            </form>
                        </div>
                    </div>
                    <a href="#" class="comment-button">Comentar</a>
                    <a href="#" class="share-button">Copiar Link</a>
                    <a href="#" class="report-button">Denunciar</a>
                </div>
                <div class="comments-section">
                    <form action="{% url 'epicfantasiesapp:comentario' lista_view_individual.historia.id %}" method="post" class="comment-input comment-form">
                        {% csrf_token %}
                        <input type="text" name="comment" placeholder="Escreva um comentário...">
                        <button type="submit" class="send-comment">Enviar</button>
                    </form>
                    {% for comentario_individual in lista_view_individual.comentario %}
                        <div class="comment">
                            <img src="{{comentario_individual.user.perfil.get_foto_perfil_url}}" alt="Avatar" class="comment-avatar">
                            <div class="comment-content">
                                <p class="comment-author">{{comentario_individual.user.username}}</p>
                                <p class="comment-text">{{comentario_individual.valor_comentario}}</p>
                            </div>
                        </div>                        
                    {% endfor %}

                </div>
            </div>
        {% endfor %}

    </div>

{% endblock content %}

epicfantasiesapp/templates/epicfantasiesapp/pages/meuperfilusuario.html
{% extends 'global/base.html' %}

{% block title %}Meu Perfil | {% endblock title %}

{% block content %}
<div class="profile-container">
    <aside>
        <div class="profile-menu">
            <ul>
                <li class="active"><a href="#overview">Visão Geral</a></li>
                <li><a href="#editar">Editar Dados</a></li>                  
                <li><a href="#historias">Criar Histórias</a></li>
                <li><a href="#biblioteca">Minha Biblioteca</a></li>
            </ul>
        </div>
    </aside>
    <main>
        <section id="overview" class="tab-content active">
            <div class="circle">
                {% if request.user.perfil.foto_perfil%}
                    <img src="{{user.perfil.get_foto_perfil_url}}">
                {% else %}
                    <img src="https://placehold.co/200x200">
                {% endif %}
                
            </div>
            <br>
            <h2>Olá, {{user.username}} </h2>
            <p><b>Data de criação do perfil:</b> {{user.perfil.data_criacao|date:"d/m/Y H:i"}} </p>
            <p><b>Nome:</b> {{user.first_name}}</p>
            <p><b>Último nome:</b> {{user.last_name}}</p>
            <p><b>Redes Socias:</b></p>
            {% if user.redessociais.instagram != "None"%}
                <p>&emsp;&emsp;<b>Instagram:</b> {{user.redessociais.instagram}}</p>                   
            {% endif %}
            {% if user.redessociais.facebook != "None"%}
                <p>&emsp;&emsp;<b>Facebook:</b> {{user.redessociais.facebook}}</p>
            {% endif %} 
            {% if user.redessociais.twitter != "None"%}
                <p>&emsp;&emsp;<b>X (antigo Twitter):</b> {{user.redessociais.twitter}}</p>
            {% endif %} 
            {% if user.redessociais.tiktok != "None"%}
                <p>&emsp;&emsp;<b>TikTok:</b> {{user.redessociais.tiktok}}</p>
            {% endif %} 



            
            
            
            
        </section>           
        <section id="editar" class="tab-content">
            <h2>Editar Dados</h2>
            <form action="{% url 'epicfantasiesapp:meuPerfilUpdate' %}" method="POST" enctype="multipart/form-data" class="profile-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="first_name">Primeiro Nome:</label>
                    <input type="text" id="first_name" name="first_name" value="{{ user.first_name }}" class="form-control">
                </div>
                <div class="form-group">
                    <label for="last_name">Segundo Nome:</label>
                    <input type="text" id="last_name" name="last_name" value="{{ user.last_name }}" class="form-control">
                </div>
                <div class="form-group">
                    <label for="foto_perfil">Foto de Perfil:</label>
                    <input type="file" id="foto_perfil" name="foto_perfil" class="form-control-file">
                </div>
                <div class="form-group">
                    <label for="instagram">Instagram:</label>
                    <input type="text" id="instagram" name="instagram" value="{{ user.redessociais.instagram }}" class="form-control">
                </div>
                <div class="form-group">
                    <label for="facebook">Facebook:</label>
                    <input type="text" id="facebook" name="facebook" value="{{ user.redessociais.facebook }}" class="form-control">
                </div>
                <div class="form-group">
                    <label for="twitter">Twitter:</label>
                    <input type="text" id="twitter" name="twitter" value="{{ user.redessociais.twitter }}" class="form-control">
                </div>
                <div class="form-group">
                    <label for="tiktok">TikTok:</label>
                    <input type="text" id="tiktok" name="tiktok" value="{{ user.redessociais.tiktok }}" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Atualizar</button>
            </form>
            
        </section>
        <section id="historias" class="tab-content">
            <h2>Criar Histórias</h2>
            <form action="{% url 'epicfantasiesapp:meuPerfilStory' %}" method="POST" enctype="multipart/form-data" class="story-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="titulo">Título:</label>
                    <input type="text" id="titulo" name="titulo" class="form-control" >
                </div>
                <div class="form-group">
                    <label for="previu">Previu:</label>
                    <textarea id="previu" name="previu" class="form-control textarea-height-previu"></textarea>
                </div>
                <div class="form-group">
                    <label for="conteudo">Conteúdo:</label>
                    <textarea id="conteudo" name="conteudo" class="form-control textarea-height-conteudo"></textarea>
                </div>
                <div class="form-group"> 
                    <label for="id_categoria">Categoria da história:</label>
                    <select name="categoria" class="opcoes-de-historias" id="id_categoria"> 
                        {% for categoria in categorias_disponiveis %}
                            <option value="{{ categoria.id }}">{{ categoria.nome }}</option>
                        {% endfor %}
                    </select>
                </div>                   
                <div class="form-group">
                    <label for="foto">Foto:</label>
                    <input type="file" id="foto" name="foto" class="form-control-file">
                </div>
                <div class="form-group">
                    <label for="is_published">Deseja publicar história?</label><span>(caso não marque, essa história será exibido em sua biblioteca na área de "Não Publicadas")</span><br>
                    <input type="checkbox" id="is_published" name="is_published" value="on" class="form-control-checkbox"> <span> Sim</span>
                </div>
                <button type="submit" class="btn btn-primary">Salvar História</button>
            </form>
            
        </section>
        <section id="biblioteca" class="tab-content" class="">
            <h2>Minha Biblioteca</h2>
        <div class="container-grid-public-not-public">
            <h3>PUBLICADO</h3><h3>NÃO PUBLICADO</h3>
            
                <div class="item-grid-public">
                    <div class="flex-item-public">
                        {% for  lista_view_individual in lista_view_published  %}
                            {% include 'epicfantasiesapp/partials/historias.html' %}
                        {% endfor %}
                    </div>
                    
                </div>
            
                <div class="item-grid-not-public">
                    <div class="flex-item-not-public">
                    {% for  lista_view_individual in lista_view_not_published  %}
                        {% include 'epicfantasiesapp/partials/historias.html' %}
                    {% endfor %}
                    </div>
                </div>
                
                
            
        </div>

        </section>
    </main>
</div>

{% endblock content %}

epicfantasiesapp/templates/epicfantasiesapp/pages/paginaDeRedirecionamento.html
{% extends 'global/base.html' %}

{% block title %}Redirecionamento | {% endblock title %}

{% block content %}

    <div class="redirecionamento" >
    {% if not status%}
        <span>Envio realizado com sucesso</span>
    {% else %}
        <span>Aconteceu algum erro</span>
    {% endif %}
        <br>
        <a class="redirecionamento-botao"href="{% url "epicfantasiesapp:entrar" %}">Voltar</a>
    </div>


{% endblock content %}